on: [pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    name: Detect Secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Checkout full history to make .gitleaksignore work like it does locally

      - name: GitLeaks
        uses: gacts/gitleaks@v1 # Action page: <https://github.com/gacts/gitleaks>

      - name: Add Failure Instructions to Pull Request
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1 # Action page: <https://github.com/thollander/actions-comment-pull-request>
        with:
          message: |
            :warning: A secret was detected :warning:
            [Gitleaks](https://github.com/gitleaks/gitleaks) is an automated tool for detecting passwords or other secrets, it
            has detected high entropy strings in your PR.
